### ISSUE TITLE
Choose CSV delimiter

### ISSUE THREAD

**Issue by gemzon** [brianlagunas/Excel2Json#1]
For a future version, you may consider different delimiters (CultureInfo), especially now when you're going _live worldwide_ ...
Not all use commas as separator 😁

I don't know if TS has the ability to get `CultureInfo.CurrentCulture.TextInfo.ListSeparator`, if not, you may need a settings option.
Else, you for sure have a serious bug in some countries 😱

**Comment by brianlagunas** [comment]
done!
