### ISSUE TITLE
Site is not meant for Mobile

### ISSUE THREAD

**Issue by brianlagunas** [brianlagunas/Excel2Json#18]
This app is not meant to be used on mobile devices. I need to think of a way to show a message or warning for mobile users. This should only be used on tablets and desktops.

**Comment by AlexHedley** [comment]
Any of these worth trying:

https://stackoverflow.com/questions/11381673/detecting-a-mobile-browser

**Comment by brianlagunas** [comment]
Possibly, however, I was hoping for something simpler that didn't require another dependency.  That answer was posted back in 2012. You would think this would have a better solution by now LOL

Do you think I should just detect the mobile browser and redirect to a page that says something like "not supported on mobile, but thanks for trying"?

**Comment by brianlagunas** [comment]
After looking into this more, both the excel spreadsheet and monaco editor are not built for mobile devices. This will remain a desktop only application.
