### ISSUE TITLE
What about nested objects?

### ISSUE THREAD

**Issue by ricciardelli** [brianlagunas/Excel2Json#35]
How can I produce something like this from an Excel?

```json
[
    {
        "name": "scott",
        "surname": "lang",
        "profile":  {
            "type": "ok",
            "active": true
         }
    }
]
```

**Comment by brianlagunas** [comment]
This tool doesn’t support nested data like that. It’s solely meant to convert Excel table data to Json. Theoretically I could probably add support by using named ranges and some special syntax, but this isn’t something a plan on doing anytime soon. 

Good question though.
