### ISSUE TITLE
Email Verification.

### ISSUE THREAD

**Issue by Steve2106** [brianlagunas/Excel2Json#40]
Hi There,
When I try to login it says my email has not been verified but I have no way of asking for the verification email.
What should I do?

Best Regards,

Steve Wilson.

**Comment by brianlagunas** [comment]
Try using this:

https://excel2json.io/account/resend-confirmation

Also, make sure to check your spam. I use SendGrid to send the emails.

**Comment by brianlagunas** [comment]
I haven't heard back so I'm going to assume this was figured out
