### ISSUE TITLE
Excel file not parsed correctly

### ISSUE THREAD

**Issue by Eyilink** [brianlagunas/Excel2Json#41]
Hi , 

I'am parsing my excel file using your website but the first column (id) 
[2a Données7 juillet.xlsx](https://github.com/user-attachments/files/16119536/2a.Donnees7.juillet.xlsx)
 isn't take into account when I transform my excel fyle into json file.

**Comment by brianlagunas** [comment]
My guess is because your ID column is not part of the table, and only the table is being parsed.
